# Generated by Django 2.2.4 on 2019-12-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='faq_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_answer1',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_answer2',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_answer3',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_answer4',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_answer5',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_answer6',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_answer7',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_question',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_question1',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_question2',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_question3',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_question4',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_question5',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_question6',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='land',
            name='faq_question7',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_for',
            field=models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_for1',
            field=models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_for2',
            field=models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_for3',
            field=models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_for4',
            field=models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_for5',
            field=models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_for6',
            field=models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_for7',
            field=models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера'),
        ),
        migrations.AlterField(
            model_name='land',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='land',
            name='link_url1',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='land',
            name='link_url2',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='land',
            name='link_url3',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='land',
            name='link_url4',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='land',
            name='link_url5',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='land',
            name='link_url6',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='land',
            name='link_url7',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на магазин'),
        ),
    ]
