# Generated by Django 2.2.4 on 2019-12-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0002_auto_20191227_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='ссылка на магазин')),
                ('image_for', models.ImageField(blank=True, null=True, upload_to='ecoc/photos/', verbose_name='картинка партнера')),
            ],
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_for',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_for1',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_for2',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_for3',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_for4',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_for5',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_for6',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_for7',
        ),
        migrations.RemoveField(
            model_name='land',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='land',
            name='link_url1',
        ),
        migrations.RemoveField(
            model_name='land',
            name='link_url2',
        ),
        migrations.RemoveField(
            model_name='land',
            name='link_url3',
        ),
        migrations.RemoveField(
            model_name='land',
            name='link_url4',
        ),
        migrations.RemoveField(
            model_name='land',
            name='link_url5',
        ),
        migrations.RemoveField(
            model_name='land',
            name='link_url6',
        ),
        migrations.RemoveField(
            model_name='land',
            name='link_url7',
        ),
    ]
