# Generated by Django 2.0.2 on 2020-01-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0004_auto_20191227_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='event'),
        ),
    ]
