# Generated by Django 2.0.2 on 2020-01-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0005_shop_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='picture_little',
            field=models.FileField(upload_to='ecoc/photos/', verbose_name='первая маленькая картинка, вторая сноска'),
        ),
        migrations.AlterField(
            model_name='land',
            name='picture_little1',
            field=models.FileField(upload_to='ecoc/photos/', verbose_name='вторая маленькая картинка, вторая сноска'),
        ),
        migrations.AlterField(
            model_name='land',
            name='picture_little2',
            field=models.FileField(upload_to='ecoc/photos/', verbose_name='третья маленькая картинка, вторая сноска'),
        ),
    ]
