# Generated by Django 2.0.2 on 2020-01-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0006_auto_20200113_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='text11',
            field=models.TextField(blank=True, null=True, verbose_name='Вторая колонки сноски1'),
        ),
    ]
